vlib work

vcom ../Quartus/altpll_progetto_comp.vhd
vcom ../Quartus/FSM_attesa.vhd
vcom ../Quartus/UartProgetto_comp.vhd
vcom ../Quartus/dec_command/dec_command.vhd
vcom ../Quartus/dec_command/Detect_1.vhd
vcom ../Quartus/dec_command/Detect_2.vhd
vcom ../Quartus/dec_command/Detect_3.vhd
vcom ../Quartus/dec_command/Detect_4.vhd
vcom ../Quartus/dec_command/FSM_dec_command.vhd
vcom ../Quartus/dec_command/lpm_ff_1.vhd
vcom ../Quartus/dec_command/lpm_ff_2.vhd
vcom ../Quartus/dec_command/L_Detect.vhd
vcom ../Quartus/dec_command/TB_dec_command.vhd
vcom ../Quartus/out_encoder/const.vhd
vcom ../Quartus/out_encoder/FSM_out_enc.vhd
vcom ../Quartus/out_encoder/lpm_counter0.vhd
vcom ../Quartus/out_encoder/lpm_mux_addr.vhd
vcom ../Quartus/out_encoder/lpm_rom_0.vhd
vcom ../Quartus/out_encoder/output_encoder.vhd
vcom ../Quartus/out_encoder/out_gen_lpm_counter0.vhd
vcom ../Quartus/out_encoder/out_gen_lpm_mux0.vhd
vcom ../Quartus/out_encoder/tb_output_encoder.vhd
vcom ../Quartus/out_encoder/simulation/qsim/work/output_encoder/_primary.vhd
vcom ../Quartus/out_encoder/simulation/qsim/work/output_encoder_vlg_check_tst/_primary.vhd
vcom ../Quartus/out_encoder/simulation/qsim/work/output_encoder_vlg_sample_tst/_primary.vhd
vcom ../Quartus/out_encoder/simulation/qsim/work/output_encoder_vlg_vec_tst/_primary.vhd
vcom ../Quartus/pilotaggio_led/FSM_Pilotaggio_LED.vhd
vcom ../Quartus/pilotaggio_led/lpm_decoder_LEDS_pilot.vhd
vcom ../Quartus/pilotaggio_led/Pilotaggio_LED2.vhd
vcom ../Quartus/pilotaggio_led/TB_Pilotaggio_LED_new.vhd
vcom ../Quartus/random_time_gen/Contatore_Tempo_random.vhd
vcom ../Quartus/random_time_gen/lpm_mult0_Random_Number_Gen.vhd
vcom ../Quartus/random_time_gen/lpm_shiftreg0_LFSR_RANDOM.vhd
vcom ../Quartus/random_time_gen/Random_Time_Generator.vhd
vcom ../Quartus/random_time_gen/TB_Random_Number.vhd
vcom ../Quartus/random_time_gen/TC_tempo_attesa.vhd
vcom ../Quartus/random_time_gen/XOR_LFSR.vhd
vcom ../Quartus/rivelatore_riflessi/counter_tempo_riflessi.vhd
vcom ../Quartus/rivelatore_riflessi/lpm_counter_ms.vhd
vcom ../Quartus/rivelatore_riflessi/ms_detect.vhd
vcom ../Quartus/rivelatore_riflessi/Rilevatore_Riflessi_Completo.vhd
vcom ../Quartus/rivelatore_riflessi/TB_Progetto_completo.vhd
vcom ../Quartus/uart/quartus/RX/AND_clk_div.vhd
vcom ../Quartus/uart/quartus/RX/AND_Decisore.vhd
vcom ../Quartus/uart/quartus/RX/AND_Edge_Detector.vhd
vcom ../Quartus/uart/quartus/RX/AND_NUM_BIT.vhd
vcom ../Quartus/uart/quartus/RX/Decisore.vhd
vcom ../Quartus/uart/quartus/RX/FSM_RX.vhd
vcom ../Quartus/uart/quartus/RX/invert.vhd
vcom ../Quartus/uart/quartus/RX/lpm_counter_RX_MOD_16.vhd
vcom ../Quartus/uart/quartus/RX/lpm_counter_RX_MOD_32.vhd
vcom ../Quartus/uart/quartus/RX/lpm_shiftreg_RX_LEFT_EDGE.vhd
vcom ../Quartus/uart/quartus/RX/lpm_shiftreg_RX_RIGHT_8_BIT.vhd
vcom ../Quartus/uart/quartus/RX/lpm_shiftreg_RX_RIGHT_9.vhd
vcom ../Quartus/uart/quartus/RX/RX.vhd
vcom ../Quartus/uart/quartus/RX/TB_RX.vhd
vcom ../Quartus/uart/quartus/TX/and_gate_4.vhd
vcom ../Quartus/uart/quartus/TX/and_gate_8.vhd
vcom ../Quartus/uart/quartus/TX/FSM_TX.vhd
vcom ../Quartus/uart/quartus/TX/lpm_counter_TX.vhd
vcom ../Quartus/uart/quartus/TX/lpm_counter_TX_MOD_10.vhd
vcom ../Quartus/uart/quartus/TX/lpm_ff_0.vhd
vcom ../Quartus/uart/quartus/TX/lpm_mux0.vhd
vcom ../Quartus/uart/quartus/TX/lpm_shiftreg0.vhd
vcom ../Quartus/uart/quartus/TX/TB_TX.vhd
vcom ../Quartus/uart/quartus/TX/TX.vhd
vcom ../Quartus/uart/quartus/UART/altpll0.vhd
vcom ../Quartus/uart/quartus/UART/inverter.vhd
vcom ../Quartus/uart/quartus/UART/TB_TX_UART.vhd
vcom ../Quartus/uart/quartus/UART/TB_UART.vhd
vcom ../Quartus/uart/quartus/UART/UART.vhd

quit -f